"""empty message

Revision ID: 3f102771fae7
Revises: d5659263b688
Create Date: 2023-01-28 11:13:05.188584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f102771fae7'
down_revision = 'd5659263b688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mile_goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mile_goal', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
