"""empty message

Revision ID: c39a06ef1215
Revises: 8759d9183c4e
Create Date: 2023-02-03 11:55:30.296733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39a06ef1215'
down_revision = '8759d9183c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('goal', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'goal')
    # ### end Alembic commands ###
